# Copyright (c) 2020 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.6'

services:
## Define VideoIngestion service
  ia_video_ingestion:
    depends_on:
      - ia_video_common
      - ia_openvino_base
    build:
      context: $PWD/../VideoIngestion
      dockerfile: $PWD/../VideoIngestion/Dockerfile
      args:
        EII_VERSION: ${EII_VERSION}
        EII_UID: ${EII_UID}
        EII_USER_NAME: ${EII_USER_NAME}
        # set CMAKE_BUILD_TYPE value to "Debug" to generate debug symbols
        CMAKE_BUILD_TYPE: "Release"
        CMAKE_INSTALL_PREFIX: ${EII_INSTALL_PATH}
        OPENVINO_IMAGE: ${OPENVINO_IMAGE}
        RUN_TESTS: "OFF"
    image: ${DOCKER_REGISTRY}openedgeinsights/ia_video_ingestion:${EII_VERSION}
    container_name: ia_video_ingestion
    hostname: ia_video_ingestion
    restart: unless-stopped
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    ipc: "none"
    environment:
      AppName: "VideoIngestion"
      DEV_MODE: ${DEV_MODE}
      PROFILING_MODE: ${PROFILING_MODE}
      no_proxy: ${RTSP_CAMERA_IP},${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
      # Setting GENICAM value to the respective camera/GenTL producer which needs to be used
      GENICAM: "Matrix_Vision"
      # Setting the GST log levels
      # The env variable will set WARNING level 2 for gencamsrc plugin and none for other plugins
      GST_DEBUG: "0,gencamsrc:2"
      # Provisioning related variable
      CertType: "zmq"
    ports:
      - 64013:64013
    networks:
      - eii
    volumes:
      - "vol_eii_socket:${SOCKET_DIR}"
      - "/var/tmp:/var/tmp"
    privileged: true

    devices:
      # Following devices under /dev filesystem will be needed based on usecase
      # dri - GPU
      # ion - VPU
      # USB camera devices
      # Selective mount can be done for deployment
      - "/dev/dri:/dev/dri"
      - "/dev/ion:/dev/ion"
      - "/dev/bus/usb: /dev/bus/usb"
    secrets:
      - ca_etcd
      - etcd_VideoIngestion_cert
      - etcd_VideoIngestion_key

secrets:
  etcd_VideoIngestion_cert:
    file: provision/Certificates/VideoIngestion/VideoIngestion_client_certificate.pem
  etcd_VideoIngestion_key:
    file: provision/Certificates/VideoIngestion/VideoIngestion_client_key.pem
